[package]
name = "lang-2"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.21.0"


[dependencies]
lalrpop = "0.21.0"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
